# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI CD

on:
  push:
  pull_request:
    types: [opened]

jobs:
  karma:
    name: Developer build and Karma tests in Node.js matrix

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build app in development mode
        run: |
          npm ci
          npm run build --if-present
      - name: Run Karma tests and measure coverage
        run: npm run test:ci
      - name: Upload coverage to CodeCov
        run: |
          npm install codecov
          ./node_modules/.bin/codecov

  protractor:
    name: Production build and Protractor tests in browser matrix

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Build app in production mode
        run: |
          npm ci
          npm run build:prod --if-present
      - name: Run e2e tests
        run: |
          npx webdriver-manager update --standalone=false --chrome=true --gecko=false --versions.chrome 98.0.4758.80
          npm run e2e:ci

  deploy:
    name: Deploy to GitHub Pages

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    needs: [karma, protractor]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          sed -i "s/^\(\s*commit: '\)[^']*\('.*\)/\1$(git rev-parse --short HEAD)\2/" src/environments/buildinfo.ts
          sed -i "s/^\(\s*lastChange: '\)[^']*\('.*\)/\1$(TZ=UTC git log -1 --format=%cd --date='format-local:%Y-%m-%d %H:%M:%S')\2/" src/environments/buildinfo.ts
          sed -i "s/^\(\s*buildTime: '\)[^']*\('.*\)/\1$(date --utc +'%Y-%m-%d %H:%M:%S')\2/" src/environments/buildinfo.ts
          cat src/environments/buildinfo.ts
          npm run -- ng build --aot --build-optimizer --progress --base-href /WildCards/
          npm install angular-cli-ghpages
          ./node_modules/.bin/angular-cli-ghpages --dir dist/app --no-silent --name 'CI/CD deployment' --email 'devnull@cgarbs.de'
