# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build app
      run: |
        npm ci
        npm run build --if-present
    - name: Run Karma tests and measure coverage
      run: npm run test:ci
    - name: Run e2e tests
      run: |
        npx webdriver-manager update
        npm run e2e
    - name: Upload coverage to CodeCov
      run: |
        npm install codecov
        ./node_modules/.bin/codecov
